# Generated by Django 3.0.6 on 2020-11-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201126_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
