# Generated by Django 3.0.6 on 2020-11-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='name',
        ),
    ]
