# Generated by Django 3.0.6 on 2020-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='firehose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.BooleanField(default=False),
        ),
    ]
